### ISSUE TITLE
LINQ support (FYI, at least..)

### ISSUE THREAD

**Issue by PallHaraldsson** [essenciary/Genie.jl#17]
I just noticed: https://github.com/davidanthoff/LINQ.jl/tree/dev

And know of SearchLight ORM here.

I only think I know a bit at a high-level what LINQ is about - an ORM(?).

So there seems to be redundant effort here(?). [And SearchLight was already planned to have it's own package.] I've not looked into the status of LINQ.jl (or SearchLight), but I think it may be the way forward for those who do not want to write their own SQL (and I see here that PostgreSQL is no longer a dependency).

I would hate for there to be competing ORM solutions (or going to have to use two together or learn two..).

**Comment by essenciary** [comment]
Thanks, that looks very interesting. Although my experience with LINQ is very limited, I was exposed to it while dabbling in F#. LINQ and SearchLight are related, but not quite the same. 

Quoting from StackOverflow: 
LINQ is an abstraction layer for working with data which allows for set based operations, projections, filters, etc on anything that can be enumerated over. It just happens to have providers for working with relational data (LINQ to SQL, LINQ to Datasets, LINQ to Entities).

So LINQ is not an ORM, strictly speaking. 
SearchLight is an ORM, more specifically, of the ActiveRecord flavor. 

I think it's OK to have multiple ways of handling data - as they are not competing anyway. An ORM like SearchLight could sit on top of a LINQ implementation (I'd be happy to add such an adapter to avoid having to add the logic for DB query generation). Or/and Genie can provide and adapter to use LINQ instead of SearchLight.
