### ISSUE TITLE
DBI is unknown, even when present

### ISSUE THREAD

**Issue by JeffreySarnoff** [essenciary/Genie.jl#18]
on Windows

![image](https://cloud.githubusercontent.com/assets/1682118/18764114/18e435e0-80de-11e6-9d1c-0d3ff48a8492.png)

**Comment by essenciary** [comment]
Thanks

Hard to say, I don't do anything funky in there, this is handled by core Julia. 

What if you try to do "using DBI"? Does that work?

**Comment by JeffreySarnoff** [comment]
yes, it does


There seem to be two things --    
>  if you use PatternDispatch, it should be in REQUIRE (if you do not, nevermind)  
>  REQUIRE does not yet do  [what you wnat](https://groups.google.com/d/msg/julia-users/eHINShc-1XM/v2cnk0QWBgAJ) it to do    

In that thread is a suggestion to use [DeclarativePackages.jl](https://github.com/rened/DeclarativePackages.jl).

**Comment by essenciary** [comment]
No, not using PatternDispatch. 

DeclarativePackages - yes, planning on switching to it very soon, although mainly for different reasons: being able to lock package version on a project by project basis. 

Did you manage to get it working? Or have you encountered similar problems with other packages? I haven't run it on windows since 0.5 came out, just MacOS and Linux, worked fine.
