### ISSUE TITLE
Minimal working example?

### ISSUE THREAD

**Issue by randyzwitch** [essenciary/Genie.jl#20]
I've been following this project for some time, and found I have some spare VMs to mess around on! Do you have a minimum working example available so I can check this package out? 

I'm only lightly familiar with Flask, having built an app or two. So really, just something for Genie that defines a page, maybe a database export I can import...just something to get me started would be fantastic.

**Comment by essenciary** [comment]
@randyzwitch The project is still under heavy development, with things changing and breaking often. For each major set of features (grouped under a minor version) I build a test app. The test app grows in parallel with the framework. 

The important parts from a framework user's perspective are in /app and /config

In the v0.5 branch, in /app you can find the stable test app running here: 
http://genieframework.com/packages

The steps for running this test app are: 
1. clone the codebase from the v0.5 branch
2. configure the DB connection
3. run the DB setup task and the migrations
4. check the available tasks and run them to import repos 
5. start the server

(more details for each of the above steps are in the README file)

=====

However, v0.6 brings many new features and breaks some things from v0.5. 

On v0.6 I'm developing a blog / CMS as the test app. The process is similar to v0.5 but right now things are a bit broken in v0.6.3 due to my work on implementing the authorization features. However, I will fix it in a few days so you'll be able to run a basic Genie blog locally. 

=====

Depending on why you need it, Genie in its current state might or might not be a good idea for your project. I'm happy to give you a hand on Gitter and walk you through setting it up once I solve the authorization component.

**Comment by randyzwitch** [comment]
Thanks! I'm aware of the status, and have built quite a few packages myself. I really just wanted to see what you're up to, and maybe contribute if I can (my long-term goal would be to move juliabloggers.com to a Julia web stack to show off)

**Comment by datnamer** [comment]
@essenciary I have a  production need for a MVC framework and was wondering if it can work in it's current state?  

My primary requirements are getting it up and running without too much fiddling, a CMS for non programmers and very very minimal front end coding in CSS, HTML and JS (generating that from julia models would be better). Can it do that now, or will it be able to at some point? Or is the front end going to require normal CSS and JS?

**Comment by essenciary** [comment]
@datnamer Actually I've built something in this line as a demo/test app. It's got a password protected admin that allows editing articles using a markdown editor. On the front the app generates html for various types of pages: home, categories [lists of articles] and article page. It uses a bootstrap theme that you can replace / tweak. 

If you want to give it a try I can setup a demo for you - if it fits the bill you can then clone it and tweak it further. 

There are some simple form helpers already. You can see how they're used in the demo app -- basically if you use the right input names they'll be mapped to the models on the server, plus knowing to render validation errors, etc. 

Longer term it will ship with full UI reactive components based on Vue.js - but that's a few months away.

**Comment by datnamer** [comment]
@essenciary Thanks. That sounds amazing, but It turns out we need just more of a single page business card type of thing so we went with one of the drag and drop GUI website builders for time efficiency.

**Comment by datnamer** [comment]
hi @essenciary !  im looking at genie again for another app.

how are the views looking these days? will i need to do alot of html / JS?

if not,  how best to get started developing?  thanks

**Comment by essenciary** [comment]
@datnamer I've added 2 new demos from my Genie presentation at JuliaCon 2017
https://github.com/essenciary/genie-demo-hello-world
https://github.com/essenciary/genie-demo-tweet-stats

Also, I've uploaded the slides, it's better if you take a look at these first, they introduce the demos (look into v1.1)
https://github.com/essenciary/JuliaCon-2017-Slides
