### ISSUE TITLE
fix src/Genie.jl

### ISSUE THREAD

**Issue by anymate98** [essenciary/Genie.jl#30]
This error occurred in Solus Linux, julia v0.6
```
julia> using Genie
ERROR: LoadError: could not open file /home/khkkoj/.julia/v0.6/Genie/src/configuration.jl
Stacktrace:
 [1] macro expansion at ./REPL.jl:97 [inlined]
 [2] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading /home/khkkoj/.julia/v0.6/Genie/src/Genie.jl, in expression starting on line 8
```
The problem was in `src/Genie.jl`

in line 8,
```
include(joinpath(Pkg.dir("Genie"), "src", "configuration.jl"))
```
`configuration.jl` should be changed to `Configuation.jl` since the file name in the `src` folder is the capitalized one...

I fixed this and it ran well!

**Comment by essenciary** [comment]
Thanks, actually the fix was the other way around, the file name should've been renamed to "configuration.jl". Because my file system is case insensitive, I didn't realize that git didn't pick the file rename. 

I did it to avoid that Julia automatically includes the module. Might not be necessary as I'm also explicitly including it. But there were problems when also including SearchLight which has a file with the same name (the Configuration module would get overwriten between packages).

**Comment by essenciary** [comment]
I've configured my git to become case sensitive and committed the change (though it doesn't show on Github...).
